include:
  # Add custom dongle and a peripheral left corne
  - board: seeeduino_xiao_ble
    shield: corne_dongle dongle_display
    snippet: studio-rpc-usb-uart
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=y -DCONFIG_ZMK_STUDIO=y -DCONFIG_ZMK_STUDIO_LOCKING=n
    artifact-name: xiao_dongle

  - board: nice_nano_v2
    shield: corne_left
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: nano_corne_left

  - board: nice_nano_v2
    shield: corne_right
    cmake-args: -DCONFIG_ZMK_SPLIT_ROLE_CENTRAL=n
    artifact-name: nano_corne_right

  # reset_settings
  - board: nice_nano_v2
    shield: settings_reset
    artifact-name: nano_reset_settings

  - board: seeeduino_xiao_ble
    shield: settings_reset
    artifact-name: xiao_reset_settings
